server:
  port: 8080
  error:
    include-stacktrace: on_trace_param

logging:
  level:
    root: WARN
    org:
      springframework:
        boot:
          web:
            embedded:
              tomcat:
                TomcatWebServer: INFO


    #org.springframework: WARN
    #org.hibernate: ERROR
    #org.springframework.web: ERROR
    #org.springframework.security: ERROR
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  profiles:
    active: noSecurity
  jpa:
    hibernate.ddl-auto: update
    #generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/auktionera
    username: root
    password: root
      #security:
      #oauth2:
      # client:
      #  registration:
        # github:
        #   client-id:
        #   client-secret:
        #google:
        #  client-id:
        #  client-secret:
  main:
    banner-mode: off




